### ISSUE TITLE
[Security] Verify that source code and published artifacts are compatible

### ISSUE THREAD

**Issue by jenkin** [sparkfabrik/nominatim-openapi#6]
**Describe your question or point of view about a topic**
Security topic: how can the user be confident (and verify by himself!) that the published application is the same in the repository? Example: openapi specification as [source code](https://raw.githubusercontent.com/sparkfabrik/nominatim-openapi/main/docs/nominatim.openapi.json) and as [published resource](https://sparkfabrik.github.io/nominatim-openapi/nominatim.openapi.json). Two different URLs, same resource?

**Comment by jenkin** [comment]
The state-of-the-art integrity check for static files served by a web server is SRI: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by paolomainardi** [comment]
Okay, reading the spec, basically, from the producer side, we should start by producing the checksum.

**Comment by paolomainardi** [comment]
To do that, we should start by creating GitHub (pre)-releases and attach the checksum as part of the artifacs.

**Comment by jenkin** [comment]
A simple `nominatim.openapi.json.checksum`?

Generated by a pre-commit (also checked by a pre-push) hook or by a GitHub action?

**Comment by jenkin** [comment]
Ok, now the git hooks to locally compute and verify checksum are ready... When we'll [create a release](https://github.com/sparkfabrik/nominatim-openapi/releases/new), we'll upload both the spec and the checksum.

@paolomainardi Feel free to reopen this issue if you have more suggestions, thanks!
